### ISSUE TITLE
"Asset Type Received" Error & "Failed To Fetch User" Error

### ISSUE THREAD

**Issue by thebrokendoggo** [LockpickInteractive/Rbx2Source#20] opened 2023-03-28 20:02 UTC
I keep getting this error every time I open up the application:
![Error 2](https://user-images.githubusercontent.com/89817436/228352226-a842b77b-16e9-4243-9510-8798063f9ee4.PNG)

Also, I've been typing in my username (and other usernames) but it keeps giving this error message:
![Error](https://user-images.githubusercontent.com/89817436/228353083-b3a9684d-2c18-411d-84cd-599e6d65f342.PNG)

**Comment by qfoxb** [comment] 2023-03-28 21:06
Duplicate of #18, this is still an ongoing issue and i still need to get to the bottom of it.

**Closed by qfoxb** 2023-03-28 21:06 UTC
Labels: duplicate

**Comment by qfoxb** [comment] 2023-03-28 21:07
This is technically not the same error message but they are caused by the same thing, hence the duplicate close
